// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaL1Rhg-dLdk93WrAY4eBpZXhsgTqIzrc',
    appId: '1:1018227793260:web:436ef1346c2cf2eb80e749',
    messagingSenderId: '1018227793260',
    projectId: 'flutter-expensetracker',
    authDomain: 'flutter-expensetracker.firebaseapp.com',
    storageBucket: 'flutter-expensetracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfvsxWI3-VOm6MFvXNXlMWaph58RMwZ-A',
    appId: '1:1018227793260:android:b875c786bf18e82380e749',
    messagingSenderId: '1018227793260',
    projectId: 'flutter-expensetracker',
    storageBucket: 'flutter-expensetracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXfWVYB-YmfxRoQmZGxTOIrC_eTnEzVo',
    appId: '1:1018227793260:ios:f722826d76746dbc80e749',
    messagingSenderId: '1018227793260',
    projectId: 'flutter-expensetracker',
    storageBucket: 'flutter-expensetracker.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXfWVYB-YmfxRoQmZGxTOIrC_eTnEzVo',
    appId: '1:1018227793260:ios:0787e92c1978f13480e749',
    messagingSenderId: '1018227793260',
    projectId: 'flutter-expensetracker',
    storageBucket: 'flutter-expensetracker.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
